### ISSUE TITLE
Link to ready-to-train preprocessed datasets not working

### ISSUE THREAD

**Issue by LucaWill** [daveluo/zanzibar-aerial-mapping#2]
Is it possible to get the data on an other way or to renew the dropbox link?
Best Regards

**Comment by daveluo** [comment]
Thanks for your interest! Which dropbox link isn't working for you? I just checked and both still seem to be active and downloadable.

**Comment by LucaWill** [comment]
thanks for the fast reply. I just checked and the dropbox link is working fine again.
